import type { Metadata } from "next";
import { Inter, Anuphan } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const anuphan_ = Anuphan({
  variable: "--font-anuphan",
  subsets: ["thai", "latin"],
})

const inter_ = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Yaniyaa - อ่านนิยายออนไลน์ฟรี",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 🟢 1. เติม suppressHydrationWarning เพื่อป้องกัน React บ่นเรื่อง Hydration Mismatch
    <html lang="th" suppressHydrationWarning>
      <head>
        {/* 🟢 2. แทรก Script เข้าไปจัดการคลาส .dark ตั้งแต่เสี้ยววินาทีแรกที่เบราว์เซอร์อ่านไฟล์ */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                // ดักเช็คคีย์ชื่อ 'theme-storage' (ของ Zustand) หรือ 'theme' แบบทั่วไป
                const savedTheme = localStorage.getItem('theme-storage') || localStorage.getItem('theme');
                let isDark = savedTheme === 'dark';
                
                // ถ้าเป็น Object ของ Zustand ให้แกะเข้าไปดูค่าข้างใน state
                if (!isDark && savedTheme) {
                  const parsed = JSON.parse(savedTheme);
                  isDark = parsed?.state?.theme === 'dark' || parsed?.theme === 'dark';
                }
                
                if (isDark) {
                  document.documentElement.classList.add('dark');
                } else {
                  document.documentElement.classList.remove('dark');
                }
              } catch (_) {}
            `,
          }}
        />
      </head>
      <body
        className={`${anuphan_.variable} ${inter_.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}